name = "thomas/agritracechain"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'thomas/agritracechain'"

[repository]
user = "thomas"
project = "agritracechain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"
[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.0"
source = "github"
[config]

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"
